### ISSUE TITLE
Hover efektleri mobilde de görünüyor

### ISSUE THREAD

**Issue by furkantaskin** [cratersoft/bumerangapp#2]
Mobil cihazlarda hover efekti düzgün çalışmıyor. Bu kısımda hover destekli cihazlarda gösterimi uygulanmalı.  Örneğin:

```scss
@media (hover:hover){
  &:hover{
    background-color: #000
  }
}
```
